# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: jupyter-fs
has_binder: true
has_settings: false
kind: frontend-and-server
labextension_name: jupyter-fs
project_short_description: A JupyterLab extension (fs aware).
python_name: jupyter_fs
repository: https://github.com/YUUU23/nb-fs-commit.git
test: false

